name: frontend-deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Pull Docker image from Docker Hub
              run: |
                  docker pull devhvun/portfolio-frontend:latest

            - name: Set up SSH key
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to server
              run: |
                  ssh -o StrictHostKeyChecking=no -p 20022 gignomad@158.179.165.167 'docker pull devhvun/portfolio-frontend:latest && docker run -d -p 3000:3000 devhvun/portfolio-frontend:latest'
